name: CI
on:
  push:
    branches: [master]
jobs:
  pharynx:
    name: build phar
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - run: composer install --ignore-platform-reqs
      - uses: SOF3/pharynx@v0.2
        id: pharynx
        with:
          additional-assets: |
            icon.png
      - uses: actions/upload-artifact@v4
        with:
          name: BedwarsPM.phar
          path: ${{steps.pharynx.outputs.output-phar}}
